config/routes.rb
Casual::Application.routes.draw do
  root 'home#index'
  get "contact/index"
  get "service/index"
  get "about/index"
  get "home/index"
  post "contact/contact"

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end

  def show
  	@about = params[:name]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end

  def show
  	@contact = params[:name]
  end

  def contact
  	UserMailer.contact_email(params[:name], params[:email], params[:phone],
  		params[:message]).deliver
  	flash[:notice]= "Email Sent! Thank you!"
  	redirect_to '/'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController
  def index
  end

  def show
  	@service = params[:name]
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/views/about/index.html.erb
<!DOCTYPE html>
<html lang="en">
    <div class="container">

        <div class="row">
            <div class="box col-md-offset-1 col-md-10">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">About <strong>Raine Makela</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-md-6">
                    <%= image_tag "chiro2.jpeg", class: 'img-responsive img-full' %>

                </div>
                <div class="col-md-6">
                    <p>This is a great place to introduce your company or project and describe what you do.</p>
                    <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets.</p>
                    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

      <!--   <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Our <strong>Team</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-sm-4 text-center">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                    <h3>John Smith
                        <small>Job Title</small>
                    </h3>
                </div>
                <div class="col-sm-4 text-center">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                    <h3>John Smith
                        <small>Job Title</small>
                    </h3>
                </div>
                <div class="col-sm-4 text-center">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                    <h3>John Smith
                        <small>Job Title</small>
                    </h3>
                </div> -->
                <div class="clearfix"></div>
            </div>
        </div>

    </div>
    <!-- /.container -->

</body>

</html>

app/views/about/show.html.erb
<% begin %>
	<%= render @about %>
<% rescue %>
	<h1>about what???</h1>
<% end %>

app/views/blog/show.html.erb
<% begin %>
	<%= render @blog %>
<% rescue %>
	<h1>about what???</h1>
<% end %>

app/views/contact/index.html.erb
<!DOCTYPE html>
<html lang="en">
<section class='contact'>
    <div class="container">
        <div class="row">
             <div class="box col-md-offset-1 col-md-10">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Contact <strong>Raine</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-md-6 col-md-offset-1">
                    <%= image_tag "chiro6.jpeg"%>
                </div>
                <div class="col-md-4">
                    <p>Phone: <strong>+358407303821</strong>
                    </p>
                    <p>Email: <strong>raine.makela@pp1.inet.fi</strong>
                    </p>
                    <p>Address: <strong>Pyolovuorentie 101<br>32700 Huittinen<br>Finland</strong>
                    </p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="row">
            <div class="box col-md-offset-1 col-md-10">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Contact <strong>form</strong>
                    </h2>
                    <hr>
                    <p>This contact form is just the form elements, it is not a working form. You will have to make the form work by yourself, or take it out if you can't figure out how to make it work.</p>
                    <%= form_tag('/contact/contact', role: 'form') do %>
                        <div class="row">
                            <div class="form-group col-lg-4">
                                <label>Name</label>
                                <input type="text" name='name' class="form-control">
                            </div>
                            <div class="form-group col-lg-4">
                                <label>Email Address</label>
                                <input type="email" name='email' class="form-control">
                            </div>
                            <div class="form-group col-lg-4">
                                <label>Phone Number</label>
                                <input type="tel" name='phone' class="form-control">
                            </div>
                            <div class="clearfix"></div>
                            <div class="form-group col-lg-12">
                                <label>Message</label>
                                <textarea class="form-control" name='message' rows="6"></textarea>
                            </div>
                            <div class="form-group col-lg-12">
                                <button type="submit" class="btn btn-default">Submit</button>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->

    

</body>
</section>
</html>

app/views/contact/show.html.erb
<% begin %>
	<%= render @contact %>
<% rescue %>
	<h1>about what???</h1>
<% end %>

app/views/home/index.html.erb
  <section class='home'>  
    <div class="container">

        <div class="row">
             <div class="box col-md-offset-1 col-md-10">
                <div class="col-md-8 col-md-offset-2 text-center">
                    <div id="carousel-example-generic" class="carousel slide">
                        <!-- Indicators -->
                        <ol class="carousel-indicators hidden-xs">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                            <div class="item active">
                            	<%= image_tag "chiropractic.jpg", class: 'img-responsive img-full' %>
                            </div>
                            <div class="item">
                            	<%= image_tag "chiropractic2.jpg", class: 'img-responsive img-full' %>
                            </div>
                            <div class="item">
                            	<%= image_tag "Spine.jpg", class: 'img-responsive img-full' %>
                            </div>
                        </div>

                        <!-- Controls -->
                        <!-- <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="icon-prev"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="icon-next"></span> -->
                        </a>
                    </div>
                    <h2>
                        <small>Welcome to</small>
                    </h2>
                    <h1>
                        <span class="brand-name">Chiropractic</span>
                    </h1>
                    <hr class="tagline-divider">
                    <h2>
                        <small> <strong>Raine Makela</strong></small>
                    </h2>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box col-md-offset-1 col-md-10">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Build a website <strong>worth visiting</strong>
                    </h2>
                    <hr>
                    <%= image_tag "chiro4.jpeg", class: 'img-responsive img-border img-left' %>

                    <hr class="visible-xs">
                    <p>The boxes used in this template are nested inbetween a normal Bootstrap row and the start of your column layout. The boxes will be full-width boxes, so if you want to make them smaller then you will need to customize.</p>
                    <p>A huge thanks to <a href="http://join.deathtothestockphoto.com/" target="_blank">Death to the Stock Photo</a> for allowing us to use the beautiful photos that make this template really come to life. When using this template, make sure your photos are decent. Also make sure that the file size on your photos is kept to a minumum to keep load times to a minimum.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box col-md-offset-1 col-md-10">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Beautiful boxes <strong>to showcase your content</strong>
                    </h2>
                    <hr>
                    <p>Use as many boxes as you like, and put anything you want in them! They are great for just about anything, the sky's the limit!</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
                </div>
            </div>
        </div>

    </div>
    </section>
    <!-- /.container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Raine Makela Chiropractic</title>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
</head>
<body>
	<div class="brand">Raine Makela</div>
    <div class="address-bar">Pyolonvuorentie 101 | 32700 | Huittinen, Finland | +358 40 7303 821</div>

    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                	<li><%= link_to 'home', home_index_path %>
                    </li>
                    <li><%= link_to 'about', about_index_path %>
                    </li>
                    <li><%= link_to 'services', service_index_path %>
                    </li>
                    <li><%= link_to 'contact', contact_index_path %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
	<%= yield %>
	<footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>k.alfred production</p>
                </div>
            </div>
        </div>
    </footer>
    <script>
    // Activates the Carousel
    $('.carousel').carousel({
        interval: 5000
    })
    </script>
</body>
</html>


    

app/views/service/index.html.erb
<!DOCTYPE html>
<html lang="en">



    <div class="container">

        <div class="row">
             <div class="box col-md-offset-1 col-md-10">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">List of <strong>Services</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-lg-12 text-center">
                    <img class="img-responsive img-border img-full" src="img/slide-1.jpg" alt="">
                    <h2>Post Title
                        <br>
                        <small>October 13, 2013</small>
                    </h2>
                    <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                    <a href="#" class="btn btn-default btn-lg">Read More</a>
                    <hr>
                </div>
                <!-- <div class="col-lg-12 text-center">
                    <img class="img-responsive img-border img-full" src="img/slide-2.jpg" alt="">
                    <h2>Post Title
                        <br>
                        <small>October 13, 2013</small>
                    </h2>
                    <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                    <a href="#" class="btn btn-default btn-lg">Read More</a>
                    <hr>
                </div>
                <div class="col-lg-12 text-center">
                    <img class="img-responsive img-border img-full" src="img/slide-3.jpg" alt="">
                    <h2>Post Title
                        <br>
                        <small>October 13, 2013</small>
                    </h2>
                    <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                    <a href="#" class="btn btn-default btn-lg">Read More</a>
                    <hr>
                </div>
                <div class="col-lg-12 text-center">
                    <ul class="pager">
                        <li class="previous"><a href="#">&larr; Older</a>
                        </li>
                        <li class="next"><a href="#">Newer &rarr;</a>
                        </li>
                    </ul>
                </div> -->
            </div>
        </div>

    </div>
   
</body>

</html>

app/views/service/show.html.erb
<% begin %>
	<%= render @service %>
<% rescue %>
	<h1>about what???</h1>
<% end %>